import { pgTable, serial, text, integer, numeric, boolean, timestamp, date, jsonb, uuid, time, check } from 'drizzle-orm/pg-core';

// Helper for timestamps
const timestamps = {
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
};

// B2BRegion Tables (add these exports to your schema.ts)
export const b2bsouth = pgTable('b2bsouth', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const b2bnorth = pgTable('b2bnorth', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const b2bnortheast = pgTable('b2bnortheast', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const b2binternational = pgTable('b2binternational', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const b2bkashmir = pgTable('b2bkashmir', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    // Pax 2
    pax02Std: text('pax_02_std'),
    pax02Dlx: text('pax_02_dlx'),
    pax02Prm: text('pax_02_prm'),
    // Pax 3
    pax03Std: text('pax_03_std'),
    pax03Dlx: text('pax_03_dlx'),
    pax03Prm: text('pax_03_prm'),
    // Pax 4
    pax04Std: text('pax_04_std'),
    pax04Dlx: text('pax_04_dlx'),
    pax04Prm: text('pax_04_prm'),
    // Pax 5
    pax05Std: text('pax_05_std'),
    pax05Dlx: text('pax_05_std'),
    pax05Prm: text('pax_05_prm'),
    // Pax 6
    pax06Std: text('pax_06_std'),
    pax06Dlx: text('pax_06_dlx'),
    pax06Prm: text('pax_06_prm'),
    // Pax 7
    pax07Std: text('pax_07_std'),
    pax07Dlx: text('pax_07_dlx'),
    pax07Prm: text('pax_07_prm'),
    // Pax 8
    pax08Std: text('pax_08_std'),
    pax08Dlx: text('pax_08_dlx'),
    pax08Prm: text('pax_08_prm'),
    // Pax 9
    pax09Std: text('pax_09_std'),
    pax09Dlx: text('pax_09_dlx'),
    pax09Prm: text('pax_09_prm'),
    // Pax 10
    pax10Std: text('pax_10_std'),
    pax10Dlx: text('pax_10_dlx'),
    pax10Prm: text('pax_10_prm'),
    // Pax 12
    pax12Std: text('pax_12_std'),
    pax12Dlx: text('pax_12_dlx'),
    pax12Prm: text('pax_12_prm'),
    // Pax 15
    pax15Std: text('pax_15_std'),
    pax15Dlx: text('pax_15_dlx'),
    pax15Prm: text('pax_15_prm'),
    // Seasonal
    seasonalStd: text('seasonal_std'),
    seasonalDlx: text('seasonal_dlx'),
    seasonalPrm: text('seasonal_prm'),
    ...timestamps,
});
