import { pgTable, serial, text, integer, numeric, boolean, timestamp, date, jsonb, uuid, time, check } from 'drizzle-orm/pg-core';

// Helper for timestamps
const timestamps = {
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
};

// Region Tables
export const south = pgTable('south', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const north = pgTable('north', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const northeast = pgTable('northeast', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const international = pgTable('international', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    pax2: integer('2'),
    pax3: integer('3'),
    pax4: integer('4'),
    pax5: integer('5'),
    pax6: integer('6'),
    pax7: integer('7'),
    pax8: integer('8'),
    pax9: integer('9'),
    pax10: integer('10'),
    pax11: integer('11'),
    pax12: integer('12'),
    pax13: integer('13'),
    pax14: integer('14'),
    pax15: integer('15'),
    pax20plus2: integer('20+2'),
    pax25plus2: integer('25+2'),
    pax30plus2: integer('30+2'),
    pax35plus2: integer('35+2'),
    pax40plus2: integer('40+2'),
    pax45plus2: integer('45+2'),
    pax50plus2: integer('50+2'),
    ...timestamps,
});

export const kashmir = pgTable('kashmir', {
    id: serial('id').primaryKey(),
    sl_code: text('sl_code').notNull(),
    trip_code: text('trip_code').notNull(),
    details: text('details'),
    itinerary: text('itinerary'),
    // Pax 2
    pax02Std: text('pax_02_std'),
    pax02Dlx: text('pax_02_dlx'),
    pax02Prm: text('pax_02_prm'),
    // Pax 3
    pax03Std: text('pax_03_std'),
    pax03Dlx: text('pax_03_dlx'),
    pax03Prm: text('pax_03_prm'),
    // Pax 4
    pax04Std: text('pax_04_std'),
    pax04Dlx: text('pax_04_dlx'),
    pax04Prm: text('pax_04_prm'),
    // Pax 5
    pax05Std: text('pax_05_std'),
    pax05Dlx: text('pax_05_dlx'),
    pax05Prm: text('pax_05_prm'),
    // Pax 6
    pax06Std: text('pax_06_std'),
    pax06Dlx: text('pax_06_dlx'),
    pax06Prm: text('pax_06_prm'),
    // Pax 7
    pax07Std: text('pax_07_std'),
    pax07Dlx: text('pax_07_dlx'),
    pax07Prm: text('pax_07_prm'),
    // Pax 8
    pax08Std: text('pax_08_std'),
    pax08Dlx: text('pax_08_dlx'),
    pax08Prm: text('pax_08_prm'),
    // Pax 9
    pax09Std: text('pax_09_std'),
    pax09Dlx: text('pax_09_dlx'),
    pax09Prm: text('pax_09_prm'),
    // Pax 10
    pax10Std: text('pax_10_std'),
    pax10Dlx: text('pax_10_dlx'),
    pax10Prm: text('pax_10_prm'),
    // Pax 12
    pax12Std: text('pax_12_std'),
    pax12Dlx: text('pax_12_dlx'),
    pax12Prm: text('pax_12_prm'),
    // Pax 15
    pax15Std: text('pax_15_std'),
    pax15Dlx: text('pax_15_dlx'),
    pax15Prm: text('pax_15_prm'),
    // Seasonal
    seasonalStd: text('seasonal_std'),
    seasonalDlx: text('seasonal_dlx'),
    seasonalPrm: text('seasonal_prm'),
    ...timestamps,
});

// CRM Tables
// Note: Users table usually maps to auth.users which has UUIDs. Keeping UUID here for safety if linking to Auth.
// If it fails, we revert to text.
export const users = pgTable('users', {
    id: uuid('id').primaryKey(),
    email: text('email').notNull().unique(),
    fullName: text('full_name').notNull(),
    role: text('role').notNull(),
    phone: text('phone'),
    isActive: boolean('is_active').default(true),
    ...timestamps,
});

export const leads = pgTable('leads', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    leadSource: text('lead_source').notNull(),
    customerName: text('customer_name').notNull(),
    phone: text('phone').notNull(),
    email: text('email'),
    destination: text('destination'),
    travelDates: text('travel_dates'),
    noOfPax: integer('no_of_pax'),
    noOfStaff: integer('no_of_staff'),
    leadGuestName: text('lead_guest_name'),
    pickupPoint: text('pickup_point'),
    budget: numeric('budget'),
    specialRequirements: text('special_requirements'),
    status: text('status').default('new').notNull(),
    assignedTo: uuid('assigned_to').references(() => users.id),
    assignedToName: text('assigned_to_name'), // Staff member name (ANEES, OFFICE, etc.)
    priority: text('priority').default('medium'),
    notes: text('notes'),
    createdBy: uuid('created_by').references(() => users.id),
    ...timestamps,
});

export const followUps = pgTable('follow_ups', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    leadId: text('lead_id').references(() => leads.id, { onDelete: 'cascade' }),
    followUpDate: date('follow_up_date').notNull(),
    followUpTime: time('follow_up_time'),
    notes: text('notes'),
    status: text('status').default('pending'),
    createdBy: uuid('created_by').references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const quotations = pgTable('quotations', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    leadId: text('lead_id').references(() => leads.id, { onDelete: 'cascade' }),
    quotationNumber: text('quotation_number').unique().notNull(),
    destination: text('destination').notNull(),
    travelDates: text('travel_dates').notNull(),
    noOfPax: integer('no_of_pax').notNull(),
    noOfDays: integer('no_of_days').notNull(),
    packageDetails: jsonb('package_details'),
    perHeadRate: numeric('per_head_rate').notNull(),
    totalAmount: numeric('total_amount').notNull(),
    gstAmount: numeric('gst_amount').default('0'),
    grandTotal: numeric('grand_total').notNull(),
    validityDate: date('validity_date'),
    termsConditions: text('terms_conditions'),
    status: text('status').default('draft'),
    createdBy: uuid('created_by').references(() => users.id),
    ...timestamps,
});

export const trips = pgTable('trips', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    tripNumber: text('trip_number').unique().notNull(),
    leadId: text('lead_id').references(() => leads.id),
    quotationId: text('quotation_id').references(() => quotations.id),
    customerName: text('customer_name').notNull(),
    phone: text('phone').notNull(),
    email: text('email'),
    destination: text('destination').notNull(),
    pickupPoint: text('pickup_point'),
    pickupDate: date('pickup_date').notNull(),
    dropoffDate: date('dropoff_date').notNull(),
    noOfDays: integer('no_of_days').notNull(),
    noOfPax: integer('no_of_pax').notNull(),
    perHeadRate: numeric('per_head_rate').notNull(),
    totalAmount: numeric('total_amount').notNull(),
    gstAmount: numeric('gst_amount').default('0'),
    grandTotal: numeric('grand_total').notNull(),
    tripCoordinator: uuid('trip_coordinator').references(() => users.id),
    driverName: text('driver_name'),
    busDetails: text('bus_details'),
    packageDetails: jsonb('package_details'),
    status: text('status').default('confirmed'),
    createdBy: uuid('created_by').references(() => users.id),
    ...timestamps,
});

export const vendors = pgTable('vendors', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    vendorName: text('vendor_name').notNull(),
    category: text('category').notNull(),
    contactPerson: text('contact_person'),
    phone: text('phone').notNull(),
    email: text('email'),
    address: text('address'),
    gstNumber: text('gst_number'),
    bankDetails: jsonb('bank_details'),
    paymentTerms: text('payment_terms'),
    rating: integer('rating'),
    notes: text('notes'),
    isActive: boolean('is_active').default(true),
    ...timestamps,
});

export const vendorPriceLists = pgTable('vendor_price_lists', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    vendorId: text('vendor_id').references(() => vendors.id, { onDelete: 'cascade' }),
    itemName: text('item_name').notNull(),
    location: text('location'),
    season: text('season'),
    rateType: text('rate_type'),
    rate: numeric('rate').notNull(),
    validFrom: date('valid_from'),
    validTo: date('valid_to'),
    notes: text('notes'),
    ...timestamps,
});

export const tripVendors = pgTable('trip_vendors', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    tripId: text('trip_id').references(() => trips.id, { onDelete: 'cascade' }),
    vendorId: text('vendor_id').references(() => vendors.id),
    serviceType: text('service_type').notNull(),
    serviceDate: date('service_date'),
    amount: numeric('amount').notNull(),
    paymentStatus: text('payment_status').default('pending'),
    notes: text('notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const payments = pgTable('payments', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    paymentType: text('payment_type').notNull(),
    tripId: text('trip_id').references(() => trips.id, { onDelete: 'cascade' }),
    customerName: text('customer_name'),
    amount: numeric('amount').notNull(),
    paymentMode: text('payment_mode').notNull(),
    paymentDate: date('payment_date').notNull(),
    transactionReference: text('transaction_reference'),
    receiptNumber: text('receipt_number'),
    notes: text('notes'),
    createdBy: uuid('created_by').references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const expenses = pgTable('expenses', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    expenseNumber: text('expense_number').unique().notNull(),
    tripId: text('trip_id').references(() => trips.id, { onDelete: 'cascade' }),
    vendorId: text('vendor_id').references(() => vendors.id),
    category: text('category').notNull(),
    description: text('description').notNull(),
    amount: numeric('amount').notNull(),
    expenseDate: date('expense_date').notNull(),
    paymentMode: text('payment_mode'),
    paymentStatus: text('payment_status').default('pending'),
    notes: text('notes'),
    createdBy: uuid('created_by').references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const tripReports = pgTable('trip_reports', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    customerName: text('customer_name'),
    pickupDate: text('pickup_date'),
    dropoffDate: text('dropoff_date'),
    pickupPoint: text('pickup_point'),
    destination: text('destination'),
    noOfDays: integer('no_of_days'),
    busDetails: text('bus_details'),
    driverName: text('driver_name'),
    companion: text('companion'),
    perHead: numeric('per_head'),
    noOfPax: integer('no_of_pax'),
    freeOfCost: integer('free_of_cost'),
    total: numeric('total'),
    discount: numeric('discount'),
    salesBy: text('sales_by'),
    coordinator: text('coordinator'),
    gst: numeric('gst'),
    additionalIncome: numeric('additional_income'),
    advancePaid: numeric('advance_paid'),
    leadType: text('lead_type'),
    companionFund: numeric('companion_fund'),
    totalCash: numeric('total_cash'),
    expenses: jsonb('expenses'),
    totalExpenses: numeric('total_expenses'),
    balance: numeric('balance'),
    incentive: numeric('incentive'),
    finalProfit: numeric('final_profit'),
    bookingType: text('booking_type'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const roomBookings = pgTable('room_bookings', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    checkInDate: text('check_in_date'),
    checkOutDate: text('check_out_date'),
    place: text('place'),
    noOfAdults: integer('no_of_adults'),
    noOfKids: integer('no_of_kids'),
    propertyName: text('property_name'),
    salesBy: text('sales_by'),
    sellingRate: numeric('selling_rate'),
    b2bRate: numeric('b2b_rate'),
    profit: numeric('profit'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const tripRoomBookings = pgTable('trip_room_bookings', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    tripId: text('trip_id').references(() => trips.id, { onDelete: 'cascade' }),
    place: text('place'),
    propertyName: text('property_name'),
    checkInDate: date('check_in_date'),
    checkOutDate: date('check_out_date'),
    category: text('category'),
    sharingType: text('sharing_type'),
    capacity: integer('capacity'),
    description: text('description'),
    notes: text('notes'),
    status: text('status').default('pending'),
    rate: numeric('rate'),
    adults: integer('adults'),
    children: integer('children'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});
