INSERT INTO north (
    sl_code,
    trip_code,
    details,
    itinerary,
    "2", "3", "4", "5", "6", "7", "8", "9", "10",
    "11", "12", "13", "14", "15",
    "20+2", "25+2", "30+2", "35+2", "40+2", "45+2", "50+2"
)
VALUES
(
    'SL-100',
    'FWN100',
    'INCLUSION :
2 BREAKFAST
3 LUNCH
3 DINNER
3 NIGHT STAY (QUADRUPLE SHARING)
AC VEHICLE
ALL SIGHTSEEING AS PER YOUR ITINERARY
MAJOR ENTRY TICKETS

EXCLUSIONS :
FOOD OTHER THAN MENTIONED
ADVENTURE ACTIVITIES
TAJ MAHAL MAUSOLEM TICKET
MINERAL WATER',
    NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    7700, 7200, 6600, 6400, 6200, 6100, 5950
),
(
    'SL-101',
    'FWN101',
    'INCLUSION :
3 BREAKFAST
4 LUNCH
4 DINNER
3 NIGHT STAY (QUADRUPLE SHARING)
AC VEHICLE
ALL SIGHTSEEING AS PER YOUR ITINERARY
MAJOR ENTRY TICKETS

EXCLUSIONS :
FOOD OTHER THAN MENTIONED
ADVENTURE ACTIVITIES
TAJ MAHAL MAUSOLEM TICKET
MINERAL WATER',
    NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    9450, 8900, 7950, 7750, 7500, 7400, 7200
),
(
    'SL-102',
    'FWN102',
    'INCLUSION :
4 BREAKFAST
5 LUNCH
5 DINNER
4 NIGHT STAY (QUADRUPLE SHARING)
AC VEHICLE
ALL SIGHTSEEING AS PER YOUR ITINERARY
MAJOR ENTRY TICKETS

EXCLUSIONS :
FOOD OTHER THAN MENTIONED
ADVENTURE ACTIVITIES
TAJ MAHAL MAUSOLEM TICKET
MINERAL WATER

NOTE :
ADD 500 EXTRA FOR ENTRY TICKETS FOR ADULTS GROUP',
    NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL
);
